// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dd2c7283-d82e-46ac-961c-78eb16692454",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_KuV2yWZ9N",
    "aws_user_pools_web_client_id": "22n4bp6lvkdk9233sdu2ad80fp",
    "oauth": {
        "domain": "myphotosalbumonline-cmpe.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://mqsod5del5d2dayroc7a37n7ma.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "photo-albums-online-cmpe",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
